---
title: "STAT370 (Theoretical Statistics) Individual Homework 7"
author: "Oliver Baldwin Edwards"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    fig_height: 2.7
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
library(mdsr)   
library(ggplot2)
library(mosaic)
library(knitr)
library(tidyverse)
library(dplyr)
library(GGally)
library(kableExtra)
# Load additional packages here 
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

https://bookdown.org/yihui/rmarkdown-cookbook/kableextra.html


for drop in dipsersion full model vs model with only weight:


Hypothesis:
Let βq be the rank-based slope coefficients of the predictors that are not included in the reduced model. In this case, the predictors (q = 9) being dropped are: cyl, disp, hp, drat, qsec, vs, am, gear, and carb.
H0 :βq =0,orβ1 =β2 =...=βq =0
H0 : at least one of the β1, β2, ..., βq are not equal to zero Assumptions:
Independence - satisfied assuming that the specifications of one car is independent from that of another car.
Linearity - assume to be satisfied.


The test statistic, HM, is 2.1064 on 9 and 21 degrees of freedom, and its associated p-value is 0.0768

Conclusion: Since the p-value > alpha level (set at 0.05), we fail to reject the null reduced model in favor of the larger full model. In the presence of weight already in the model, none of the other predictors are significant predictors of mpg. In other words, the reduced model accounts for about the same amount of variability in the response as the full model.