---
title: "Prediciting Hurricane Deaths"
author: Group 2 - Oliver Baldwin Edwards, Leah Johnson, Adi Arifovic
date: May 13th, 2020
output: ioslides_presentation
incremental: true
---
## Purpose
We hope to predict the log number of hurricane deaths based on variables such as maximum sustained windspeed, atmospheric pressure, and property damage from a dataset containing data on 94 named hurricanes that made landfall in the US mainland from 1950 through 2012. We would expect the number of deaths to increase as the maximum sustained windspeed and property damage increases, since it would make sense for more destructive hurricanes to also be more deadly.
# Data
## Source
We plan to use the dataset "hurricNamed" from the "DAAG" R package containing data on 94 named hurricanes that made landfall in the US mainland from 1950 through 2012. It contains information on the number of deaths, the name of the hurricane, the year of the hurricane, the damage caused by the hurricane, etc. The data is sourced from multiple places and was used in a research paper claiming that hurricanes with female names did more human damage (after adjusting for the severity of the storm) than those with male names. Therefore, the data seems fairly reliable.
## Response Variable
Our response variable is the log number of deaths that occurred due to a hurricane. The units are number of human deaths. We observe that the range of deaths are from 0 to 1836. 
## Explanatory Variables
 - LF.WindsMPH describes the maximum sustained windspeed for each hurricane in miles per hour
 - LF.PressureMB describes the atmospheric pressure at landfall in millibars
 - LF.times describes the number of times the hurricane made landfall 
 - BaseDam2014 describes the property damage caused by the hurricane in millions of 2014 US dollars
 - NDAM2014 describes the amount of damage the hurricane caused had it appeared in 2014 (no units given)
 - deaths describes the number of human deaths the hurricane caused
# Exploratory Analysis
## GGPairs
(ADD MODEL)
## Moving Forward
- The researchers first looked at kernel density estimates of our predictors, and found that  `deaths`, `NDAM2014`, and `BaseDam2014` had very non-normal/skewed kernel density estimates. The researchers found that adding a `log()` transformation to `deaths`, `NDAM2014`, and `BaseDam2014` resulted in more normal kernel density estimates and minimized the effects of the outliers. (The application of a log transformation allows the researchers to fit linear regression models (OLS and JHM) to the data.) A few of the afforementioned KDEs can be seen below:
## Kernel Density Estimation
(ADD MODEL)
- For `log_deaths`, the rectangular kernel overfits and the bandwidth selected by UCV is similarly unsuitable. The gaussian kernel looks appears to be oversmoothing. The triangular and epanechnikov kernels are similar, but the researchers decided to go with th epanechnikov kernel with bandwidth selected using BCV. The KDE looks fairly reasonable overall, and epanechnikov is generally a good choice of kernel. 
## Correlation Tests
> - We use Kendall's $\tau$ at a significance level $\alpha=0.05$, as it is robust against outliers.
> - Hypotheses tested:
> - The null hypothesis of no association (independence) $H_0: \tau \leq 0$ 
> - The alternative hypothesis of positive association $H_A: \tau > 0$. 
> - (They also tested for negative associations with the set of hypotheses $H_0: \tau \geq 0$ and $H_A: \tau < 0$.)
## Correlation Results
- log_NDAM2014, log_BaseDam2014, LF.times, and LF.WindsMPH were all significantly positively associated with log_deaths. 
- LF.PressureMB was also significantly negatively associated with log_deaths.
- ADD TABLE
## Ordinary Least Squares Regression
- Assumptions: _____ appear to be met.
- The best OLS model was the model predicting log_deaths with simply log_NDAM2014.
- ADD ^THIS MODEL
## Kolmogrov Smirnov Test
- Ran this test to check the assumption of normally distributed residuals for our above selected linear regression model.
- Hypothesis: $H_0: F(t) = F^*(t)$ & $H_A: F(t) \neq F^*(t)$ for at least one $t$
Where $F(t)$ refers to the estimated CDF of the distribution of residuals of our linear model, and $F^*(t)$ is the CDF of the normal distribution.
## Assumptions: 
> - Continuous: The test assumes that the theoretical distribution is continuous, which is reasonable.
> - Independence: This is reasonable, as there's no reason to believe the log deaths for one hurricane would affect another.
> - Parameters: This is also satisfied, we have mean = 0, and sd = 1 for the normal distribution, and neither of these is estimated. 
> - With the assumptions met, we ran the Kolmogrov Smirnov Test
## Kolmogrov Smirnov Test Results
> - We have a $p-$value of $0.7095 > 0.05$, so we fail to reject the null hypothesis at our significance level. 
> - We conclude that there is insufficient evidence to suggest that the estimated CDF of the distribution of the residuals in our linear model is significantly different to the CDF of the normal distribution. Thus, our assumptions for our linear model are met. 
## JHM
- Used this non-parametric approach to model fitting by using rank-based regression. 
- Found that the best model predicting log_deaths was again one that used only log_NDAM2014. 
- Performed drop in dispersion tests when making this decision and found that the model containing only NDAM2014 was the best model.
## Best JHM
- ADD MODEL
# Generalized Additive Model
## Fitting log_NDAM2014 to the GAM
- Lastly, attempted to fit a generalized additive model (GAM) to the data. 
- Used manual forward selection to fit the best model. 
- With an AIC of 290.8135, the researchers first found the best way to fit log_NDAM2014 was with a b-spline with the default number of degrees of freedom. 
## First GAM
- (ADD MODEL)
## Fitting LF.PressureMB to the GAM
- The best way to fit LF.PressureMB was with an s-spline with 5 degrees of freedom (while keeping the previous b-spline for log_NDAM2014).
- (ADD NEW MODEL)
## Additional Changes to the GAM
> - All other predictors increased the AIC, so the researchers decided on the GAM using a b-spline with the default number of degrees of freedom for log_NDAM2014, and  an s-spline with 5 degrees of freedom LF.PressureMB. 
> - After plotting, the LF.PressureMB scatterplot displayed a poor fit. 
> - LF.PressureMB appeared to be roughly quadratic, so it was fit with a polynomial.
## Final version of the GAM
- (ADD MODEL)
# Conclusion
Final Remarks
- 
# Questions?
